logging:
  level:
    root: INFO
    com.novles: DEBUG
  file:
    name: gateway.log
    path: ./log/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cloud:
    nacos:
      config:
        file-extension:
server:
  port: 80
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
